#!/usr/bin/env bash
set -eu -o pipefail

if [[ $(tput cols) != 100 ]]; then
	# This is silly, but there doesn't seem to be a way to override clap's detection or default width.
	echo "$0: Resize your terminal to 100 columns wide (currently $(tput cols)), then try again!" 2>&1
	exit 1
fi

DOC=README.md

cd "$(dirname "$0")/../.."
tempsection=$(mktemp)
tempdoc=$(mktemp)
trap 'rm -f "$tempsection" "$tempdoc"' EXIT
cp "$DOC" "$tempdoc"

ver=$(ynab --version|awk '{print $2}')
sed -i '' \
    -e 's/^\(Version: \)[0-9.]*$/\1'"$ver"'/' \
    -e 's/ynab-[0-9.]*-/ynab-'"$ver"'-/g' \
    -e 's/cli-for-ynab\/releases\/download\/v[0-9.]*\//cli-for-ynab\/releases\/download\/v'"$ver"'\//g' \
    -e 's/cli-for-ynab\/archive\/v[0-9.]*\./cli-for-ynab\/archive\/v'"$ver"'./g' \
    -e 's/cli-for-ynab\/tree\/v[0-9.]*/cli-for-ynab\/tree\/v'"$ver"'/g' \
    "$tempdoc"

grep -B 9999 "BEGIN AUTOGENERATED USAGE" "$tempdoc" >"$tempsection"
"etc/scripts/all_usage_markdown.sh" >>"$tempsection"
echo "" >>"$tempsection"
grep -A 9999 "END AUTOGENERATED USAGE" "$tempdoc" >>"$tempsection"
mv "$tempsection" "$tempdoc"

grep -B 9999 "BEGIN AUTOGENERATED COMPLETIONS" "$tempdoc" >"$tempsection"
rustup completions --help|grep -A 9999 "^DISCUSSION:"|grep -v '^DISCUSSION:'|sed -e 's/^    //'  -e 's/rustup/ynab/g' -e 's/^\([A-Z][A-Z][A-Z].*:\)$/#### \1/' >>"$tempsection"
echo "" >>"$tempsection"
grep -A 9999 "END AUTOGENERATED COMPLETIONS" "$tempdoc" >>"$tempsection"
mv "$tempsection" "$tempdoc"

grep -B 9999 "BEGIN AUTOGENERATED TOC" "$tempdoc" >"$tempsection"
grep '^\(## \|### \)' "$tempdoc"|grep -v "Table of contents" | while read -r l; do
    if echo "$l"|grep '^### '>/dev/null; then
        echo -n "      * " >>"$tempsection"
    else
        echo -n "  * " >>"$tempsection"
    fi
    m=$(echo "$l"|sed 's/^#* //')
	echo "[$m](#$(echo "$m"|tr '[A-Z] ' '[a-z]-'))" >>"$tempsection"
done
grep -A 9999 "END AUTOGENERATED TOC" "$tempdoc" >>"$tempsection"
mv "$tempsection" "$tempdoc"

cp "$DOC" "$DOC.$(date +%Y%m%d%H%M%S)" #@@@ NEED?
mv "$tempdoc" "$DOC"
