/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use futures::{Future, Stream};

use super::{Error, configuration};

pub struct BudgetsApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> BudgetsApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> BudgetsApiClient<C> {
        BudgetsApiClient {
            configuration: configuration,
        }
    }
}

pub trait BudgetsApi {
    fn get_budget_by_id(&self, budget_id: &str, last_knowledge_of_server: Option<i64>) -> Box<Future<Item = ::models::BudgetDetailResponse, Error = Error>>;
    fn get_budget_settings_by_id(&self, budget_id: &str) -> Box<Future<Item = ::models::BudgetSettingsResponse, Error = Error>>;
    fn get_budgets(&self, ) -> Box<Future<Item = ::models::BudgetSummaryResponse, Error = Error>>;
}


impl<C: hyper::client::Connect>BudgetsApi for BudgetsApiClient<C> {
    fn get_budget_by_id(&self, budget_id: &str, last_knowledge_of_server: Option<i64>) -> Box<Future<Item = ::models::BudgetDetailResponse, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        // @@@ MAKE SIMILAR CHANGE EVERYWHERE last_knowledge_of_server USED
        let mut query = ::url::form_urlencoded::Serializer::new(String::new());
        if let Some(last_knowledge_of_server) = last_knowledge_of_server {
            query.append_pair("last_knowledge_of_server", &last_knowledge_of_server.to_string());
        }
        let query = query.finish();
        let uri_str = format!("{}/budgets/{budget_id}{}", configuration.base_path, query, budget_id=budget_id);
        // println!("@@@ uri_str={:?}", uri_str);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let req = configuration.new_request(method, uri.unwrap());



        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::BudgetDetailResponse, _> = super::json_from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn get_budget_settings_by_id(&self, budget_id: &str) -> Box<Future<Item = ::models::BudgetSettingsResponse, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let uri_str = format!("{}/budgets/{budget_id}/settings", configuration.base_path, budget_id=budget_id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let req = configuration.new_request(method, uri.unwrap());



        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::BudgetSettingsResponse, _> = super::json_from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn get_budgets(&self, ) -> Box<Future<Item = ::models::BudgetSummaryResponse, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let uri_str = format!("{}/budgets", configuration.base_path);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let req = configuration.new_request(method, uri.unwrap());



        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::BudgetSummaryResponse, _> = super::json_from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

}
