/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures::{Future, Stream};

use super::{Error, configuration};

pub struct DeprecatedApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> DeprecatedApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> DeprecatedApiClient<C> {
        DeprecatedApiClient {
            configuration: configuration,
        }
    }
}

pub trait DeprecatedApi {
    fn bulk_create_transactions(&self, budget_id: &str, transactions: ::models::BulkTransactions) -> Box<dyn (Future<Item = ::models::BulkResponse, Error = Error>)>;
}


impl<C: hyper::client::Connect>DeprecatedApi for DeprecatedApiClient<C> {
    fn bulk_create_transactions(&self, budget_id: &str, transactions: ::models::BulkTransactions) -> Box<dyn (Future<Item = ::models::BulkResponse, Error = Error>)> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Post;

        let uri_str = format!("{}/budgets/{budget_id}/transactions/bulk", configuration.base_path, budget_id=budget_id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = configuration.new_request(method, uri.unwrap());


        let serialized = serde_json::to_string(&transactions).unwrap();
        req.headers_mut().set(hyper::header::ContentType::json());
        req.headers_mut().set(hyper::header::ContentLength(serialized.len() as u64));
        req.set_body(serialized);

        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::BulkResponse, _> = super::json_from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

}
