/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures::{Future, Stream};

use super::{Error, configuration};

pub struct TransactionsApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> TransactionsApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> TransactionsApiClient<C> {
        TransactionsApiClient {
            configuration: configuration,
        }
    }
}

pub trait TransactionsApi {
    fn create_transaction(&self, budget_id: &str, save_transactions: ::models::SaveTransactionsWrapper) -> Box<dyn (Future<Item = ::models::SaveTransactionsResponse, Error = Error>)>;
    fn get_transaction_by_id(&self, budget_id: &str, transaction_id: &str) -> Box<dyn (Future<Item = ::models::TransactionResponse, Error = Error>)>;
    fn get_transactions(&self, budget_id: &str, since_date: Option<chrono::NaiveDate>, _type: Option<::models::TransactionType>, last_knowledge_of_server: Option<i64>) -> Box<dyn (Future<Item = ::models::TransactionsResponse, Error = Error>)>;
    fn get_transactions_by_account(&self, budget_id: &str, account_id: &str, since_date: Option<chrono::NaiveDate>, _type: Option<::models::TransactionType>, last_knowledge_of_server: Option<i64>) -> Box<dyn (Future<Item = ::models::TransactionsResponse, Error = Error>)>;
    fn get_transactions_by_category(&self, budget_id: &str, category_id: &str, since_date: Option<chrono::NaiveDate>, _type: Option<::models::TransactionType>, last_knowledge_of_server: Option<i64>) -> Box<dyn (Future<Item = ::models::HybridTransactionsResponse, Error = Error>)>;
    fn get_transactions_by_payee(&self, budget_id: &str, payee_id: &str, since_date: Option<chrono::NaiveDate>, _type: Option<::models::TransactionType>, last_knowledge_of_server: Option<i64>) -> Box<dyn (Future<Item = ::models::HybridTransactionsResponse, Error = Error>)>;
    fn update_transaction(&self, budget_id: &str, transaction_id: &str, transaction: ::models::SaveTransactionWrapper) -> Box<dyn (Future<Item = ::models::TransactionResponse, Error = Error>)>;
}


impl<C: hyper::client::Connect>TransactionsApi for TransactionsApiClient<C> {
    fn create_transaction(&self, budget_id: &str, save_transactions: ::models::SaveTransactionsWrapper) -> Box<dyn (Future<Item = ::models::SaveTransactionsResponse, Error = Error>)> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Post;

        let uri_str = format!("{}/budgets/{budget_id}/transactions", configuration.base_path, budget_id=budget_id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = configuration.new_request(method, uri.unwrap());


        let serialized = serde_json::to_string(&save_transactions).unwrap();
        req.headers_mut().set(hyper::header::ContentType::json());
        req.headers_mut().set(hyper::header::ContentLength(serialized.len() as u64));
        req.set_body(serialized);

        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::SaveTransactionsResponse, _> = super::json_from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn get_transaction_by_id(&self, budget_id: &str, transaction_id: &str) -> Box<dyn (Future<Item = ::models::TransactionResponse, Error = Error>)> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let uri_str = format!("{}/budgets/{budget_id}/transactions/{transaction_id}", configuration.base_path, budget_id=budget_id, transaction_id=transaction_id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let req = configuration.new_request(method, uri.unwrap());



        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::TransactionResponse, _> = super::json_from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn get_transactions(&self, budget_id: &str, since_date: Option<chrono::NaiveDate>, _type: Option<::models::TransactionType>, last_knowledge_of_server: Option<i64>) -> Box<dyn (Future<Item = ::models::TransactionsResponse, Error = Error>)> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let mut query = ::url::form_urlencoded::Serializer::new(String::new());
        if let Some(since_date) = since_date {
            query.append_pair("since_date", &since_date.to_string());
        }
        if let Some(_type) = _type {
            query.append_pair("type", &_type.to_string());
        }
        if let Some(last_knowledge_of_server) = last_knowledge_of_server {
            query.append_pair("last_knowledge_of_server", &last_knowledge_of_server.to_string());
        }
        let query = query.finish();
        let uri_str = format!("{}/budgets/{budget_id}/transactions?{}", configuration.base_path, query, budget_id=budget_id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let req = configuration.new_request(method, uri.unwrap());



        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::TransactionsResponse, _> = super::json_from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn get_transactions_by_account(&self, budget_id: &str, account_id: &str, since_date: Option<chrono::NaiveDate>, _type: Option<::models::TransactionType>, last_knowledge_of_server: Option<i64>) -> Box<dyn (Future<Item = ::models::TransactionsResponse, Error = Error>)> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let mut query = ::url::form_urlencoded::Serializer::new(String::new());
        if let Some(since_date) = since_date {
            query.append_pair("since_date", &since_date.to_string());
        }
        if let Some(_type) = _type {
            query.append_pair("type", &_type.to_string());
        }
        if let Some(last_knowledge_of_server) = last_knowledge_of_server {
            query.append_pair("last_knowledge_of_server", &last_knowledge_of_server.to_string());
        }
        let query = query.finish();
        let uri_str = format!("{}/budgets/{budget_id}/accounts/{account_id}/transactions?{}", configuration.base_path, query, budget_id=budget_id, account_id=account_id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let req = configuration.new_request(method, uri.unwrap());



        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::TransactionsResponse, _> = super::json_from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn get_transactions_by_category(&self, budget_id: &str, category_id: &str, since_date: Option<chrono::NaiveDate>, _type: Option<::models::TransactionType>, last_knowledge_of_server: Option<i64>) -> Box<dyn (Future<Item = ::models::HybridTransactionsResponse, Error = Error>)> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let mut query = ::url::form_urlencoded::Serializer::new(String::new());
        if let Some(since_date) = since_date {
            query.append_pair("since_date", &since_date.to_string());
        }
        if let Some(_type) = _type {
            query.append_pair("type", &_type.to_string());
        }
        if let Some(last_knowledge_of_server) = last_knowledge_of_server {
            query.append_pair("last_knowledge_of_server", &last_knowledge_of_server.to_string());
        }
        let query = query.finish();
        let uri_str = format!("{}/budgets/{budget_id}/categories/{category_id}/transactions?{}", configuration.base_path, query, budget_id=budget_id, category_id=category_id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let req = configuration.new_request(method, uri.unwrap());



        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::HybridTransactionsResponse, _> = super::json_from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn get_transactions_by_payee(&self, budget_id: &str, payee_id: &str, since_date: Option<chrono::NaiveDate>, _type: Option<::models::TransactionType>, last_knowledge_of_server: Option<i64>) -> Box<dyn (Future<Item = ::models::HybridTransactionsResponse, Error = Error>)> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let mut query = ::url::form_urlencoded::Serializer::new(String::new());
        if let Some(since_date) = since_date {
            query.append_pair("since_date", &since_date.to_string());
        }
        if let Some(_type) = _type {
            query.append_pair("type", &_type.to_string());
        }
        if let Some(last_knowledge_of_server) = last_knowledge_of_server {
            query.append_pair("last_knowledge_of_server", &last_knowledge_of_server.to_string());
        }
        let query = query.finish();
        let uri_str = format!("{}/budgets/{budget_id}/payees/{payee_id}/transactions?{}", configuration.base_path, query, budget_id=budget_id, payee_id=payee_id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let req = configuration.new_request(method, uri.unwrap());



        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::HybridTransactionsResponse, _> = super::json_from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn update_transaction(&self, budget_id: &str, transaction_id: &str, transaction: ::models::SaveTransactionWrapper) -> Box<dyn (Future<Item = ::models::TransactionResponse, Error = Error>)> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Put;

        let uri_str = format!("{}/budgets/{budget_id}/transactions/{transaction_id}", configuration.base_path, budget_id=budget_id, transaction_id=transaction_id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = configuration.new_request(method, uri.unwrap());


        let serialized = serde_json::to_string(&transaction).unwrap();
        req.headers_mut().set(hyper::header::ContentType::json());
        req.headers_mut().set(hyper::header::ContentLength(serialized.len() as u64));
        req.set_body(serialized);

        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::TransactionResponse, _> = super::json_from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

}
