/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AccountsWrapper {
  #[serde(rename = "accounts")]
  accounts: Vec<::models::Account>
}

impl AccountsWrapper {
  pub fn new(accounts: Vec<::models::Account>) -> AccountsWrapper {
    AccountsWrapper {
      accounts: accounts
    }
  }

  pub fn set_accounts(&mut self, accounts: Vec<::models::Account>) {
    self.accounts = accounts;
  }

  pub fn with_accounts(mut self, accounts: Vec<::models::Account>) -> AccountsWrapper {
    self.accounts = accounts;
    self
  }

  pub fn accounts(&self) -> &Vec<::models::Account> {
    &self.accounts
  }


}



