/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BudgetDetailWrapper {
  #[serde(rename = "budget")]
  budget: ::models::BudgetDetail,
  /// The knowledge of the server
  #[serde(rename = "server_knowledge")]
  server_knowledge: i64
}

impl BudgetDetailWrapper {
  pub fn new(budget: ::models::BudgetDetail, server_knowledge: i64) -> BudgetDetailWrapper {
    BudgetDetailWrapper {
      budget: budget,
      server_knowledge: server_knowledge
    }
  }

  pub fn set_budget(&mut self, budget: ::models::BudgetDetail) {
    self.budget = budget;
  }

  pub fn with_budget(mut self, budget: ::models::BudgetDetail) -> BudgetDetailWrapper {
    self.budget = budget;
    self
  }

  pub fn budget(&self) -> &::models::BudgetDetail {
    &self.budget
  }


  pub fn set_server_knowledge(&mut self, server_knowledge: i64) {
    self.server_knowledge = server_knowledge;
  }

  pub fn with_server_knowledge(mut self, server_knowledge: i64) -> BudgetDetailWrapper {
    self.server_knowledge = server_knowledge;
    self
  }

  pub fn server_knowledge(&self) -> &i64 {
    &self.server_knowledge
  }


}



