/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BudgetSummaryWrapper {
  #[serde(rename = "budgets")]
  budgets: Vec<::models::BudgetSummary>
}

impl BudgetSummaryWrapper {
  pub fn new(budgets: Vec<::models::BudgetSummary>) -> BudgetSummaryWrapper {
    BudgetSummaryWrapper {
      budgets: budgets
    }
  }

  pub fn set_budgets(&mut self, budgets: Vec<::models::BudgetSummary>) {
    self.budgets = budgets;
  }

  pub fn with_budgets(mut self, budgets: Vec<::models::BudgetSummary>) -> BudgetSummaryWrapper {
    self.budgets = budgets;
    self
  }

  pub fn budgets(&self) -> &Vec<::models::BudgetSummary> {
    &self.budgets
  }


}



