/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BulkIdWrapper {
  #[serde(rename = "bulk")]
  bulk: ::models::BulkIds
}

impl BulkIdWrapper {
  pub fn new(bulk: ::models::BulkIds) -> BulkIdWrapper {
    BulkIdWrapper {
      bulk: bulk
    }
  }

  pub fn set_bulk(&mut self, bulk: ::models::BulkIds) {
    self.bulk = bulk;
  }

  pub fn with_bulk(mut self, bulk: ::models::BulkIds) -> BulkIdWrapper {
    self.bulk = bulk;
    self
  }

  pub fn bulk(&self) -> &::models::BulkIds {
    &self.bulk
  }


}



