/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CategoryWrapper {
  #[serde(rename = "category")]
  category: ::models::Category
}

impl CategoryWrapper {
  pub fn new(category: ::models::Category) -> CategoryWrapper {
    CategoryWrapper {
      category: category
    }
  }

  pub fn set_category(&mut self, category: ::models::Category) {
    self.category = category;
  }

  pub fn with_category(mut self, category: ::models::Category) -> CategoryWrapper {
    self.category = category;
    self
  }

  pub fn category(&self) -> &::models::Category {
    &self.category
  }


}



