/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CategoryGroupsWrapper {
  #[serde(rename = "category_groups")]
  category_groups: Vec<::models::CategoryGroupWithCategories>
}

impl CategoryGroupsWrapper {
  pub fn new(category_groups: Vec<::models::CategoryGroupWithCategories>) -> CategoryGroupsWrapper {
    CategoryGroupsWrapper {
      category_groups: category_groups
    }
  }

  pub fn set_category_groups(&mut self, category_groups: Vec<::models::CategoryGroupWithCategories>) {
    self.category_groups = category_groups;
  }

  pub fn with_category_groups(mut self, category_groups: Vec<::models::CategoryGroupWithCategories>) -> CategoryGroupsWrapper {
    self.category_groups = category_groups;
    self
  }

  pub fn category_groups(&self) -> &Vec<::models::CategoryGroupWithCategories> {
    &self.category_groups
  }


}



