/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ErrorDetail {
  #[serde(rename = "id")]
  id: String,
  #[serde(rename = "name")]
  name: String,
  #[serde(rename = "detail")]
  detail: String
}

impl ErrorDetail {
  pub fn new(id: String, name: String, detail: String) -> ErrorDetail {
    ErrorDetail {
      id: id,
      name: name,
      detail: detail
    }
  }

  pub fn set_id(&mut self, id: String) {
    self.id = id;
  }

  pub fn with_id(mut self, id: String) -> ErrorDetail {
    self.id = id;
    self
  }

  pub fn id(&self) -> &String {
    &self.id
  }


  pub fn set_name(&mut self, name: String) {
    self.name = name;
  }

  pub fn with_name(mut self, name: String) -> ErrorDetail {
    self.name = name;
    self
  }

  pub fn name(&self) -> &String {
    &self.name
  }


  pub fn set_detail(&mut self, detail: String) {
    self.detail = detail;
  }

  pub fn with_detail(mut self, detail: String) -> ErrorDetail {
    self.detail = detail;
    self
  }

  pub fn detail(&self) -> &String {
    &self.detail
  }


}



