/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ErrorResponse {
  #[serde(rename = "error")]
  error: ::models::ErrorDetail
}

impl ErrorResponse {
  pub fn new(error: ::models::ErrorDetail) -> ErrorResponse {
    ErrorResponse {
      error: error
    }
  }

  pub fn set_error(&mut self, error: ::models::ErrorDetail) {
    self.error = error;
  }

  pub fn with_error(mut self, error: ::models::ErrorDetail) -> ErrorResponse {
    self.error = error;
    self
  }

  pub fn error(&self) -> &::models::ErrorDetail {
    &self.error
  }


}


