/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PayeeLocationsWrapper {
  #[serde(rename = "payee_locations")]
  payee_locations: Vec<::models::PayeeLocation>
}

impl PayeeLocationsWrapper {
  pub fn new(payee_locations: Vec<::models::PayeeLocation>) -> PayeeLocationsWrapper {
    PayeeLocationsWrapper {
      payee_locations: payee_locations
    }
  }

  pub fn set_payee_locations(&mut self, payee_locations: Vec<::models::PayeeLocation>) {
    self.payee_locations = payee_locations;
  }

  pub fn with_payee_locations(mut self, payee_locations: Vec<::models::PayeeLocation>) -> PayeeLocationsWrapper {
    self.payee_locations = payee_locations;
    self
  }

  pub fn payee_locations(&self) -> &Vec<::models::PayeeLocation> {
    &self.payee_locations
  }


}



