/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PayeesWrapper {
  #[serde(rename = "payees")]
  payees: Vec<::models::Payee>
}

impl PayeesWrapper {
  pub fn new(payees: Vec<::models::Payee>) -> PayeesWrapper {
    PayeesWrapper {
      payees: payees
    }
  }

  pub fn set_payees(&mut self, payees: Vec<::models::Payee>) {
    self.payees = payees;
  }

  pub fn with_payees(mut self, payees: Vec<::models::Payee>) -> PayeesWrapper {
    self.payees = payees;
    self
  }

  pub fn payees(&self) -> &Vec<::models::Payee> {
    &self.payees
  }


}



