/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PayeeLocationWrapper {
  #[serde(rename = "payee_location")]
  payee_location: ::models::PayeeLocation
}

impl PayeeLocationWrapper {
  pub fn new(payee_location: ::models::PayeeLocation) -> PayeeLocationWrapper {
    PayeeLocationWrapper {
      payee_location: payee_location
    }
  }

  pub fn set_payee_location(&mut self, payee_location: ::models::PayeeLocation) {
    self.payee_location = payee_location;
  }

  pub fn with_payee_location(mut self, payee_location: ::models::PayeeLocation) -> PayeeLocationWrapper {
    self.payee_location = payee_location;
    self
  }

  pub fn payee_location(&self) -> &::models::PayeeLocation {
    &self.payee_location
  }


}



