/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SaveTransactionsWrapper {
  #[serde(rename = "transaction")]
  transaction: Option<::models::SaveTransaction>,
  #[serde(rename = "transactions")]
  transactions: Option<Vec<::models::SaveTransaction>>
}

impl SaveTransactionsWrapper {
  pub fn new() -> SaveTransactionsWrapper {
    SaveTransactionsWrapper {
      transaction: None,
      transactions: None
    }
  }

  pub fn set_transaction(&mut self, transaction: ::models::SaveTransaction) {
    self.transaction = Some(transaction);
  }

  pub fn with_transaction(mut self, transaction: ::models::SaveTransaction) -> SaveTransactionsWrapper {
    self.transaction = Some(transaction);
    self
  }

  pub fn transaction(&self) -> Option<&::models::SaveTransaction> {
    self.transaction.as_ref()
  }

  pub fn reset_transaction(&mut self) {
    self.transaction = None;
  }

  pub fn set_transactions(&mut self, transactions: Vec<::models::SaveTransaction>) {
    self.transactions = Some(transactions);
  }

  pub fn with_transactions(mut self, transactions: Vec<::models::SaveTransaction>) -> SaveTransactionsWrapper {
    self.transactions = Some(transactions);
    self
  }

  pub fn transactions(&self) -> Option<&Vec<::models::SaveTransaction>> {
    self.transactions.as_ref()
  }

  pub fn reset_transactions(&mut self) {
    self.transactions = None;
  }

}



