/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SaveTransactionWrapper {
  #[serde(rename = "transaction")]
  transaction: ::models::SaveTransaction
}

impl SaveTransactionWrapper {
  pub fn new(transaction: ::models::SaveTransaction) -> SaveTransactionWrapper {
    SaveTransactionWrapper {
      transaction: transaction
    }
  }

  pub fn set_transaction(&mut self, transaction: ::models::SaveTransaction) {
    self.transaction = transaction;
  }

  pub fn with_transaction(mut self, transaction: ::models::SaveTransaction) -> SaveTransactionWrapper {
    self.transaction = transaction;
    self
  }

  pub fn transaction(&self) -> &::models::SaveTransaction {
    &self.transaction
  }


}



